version: '2'
services:
  apigateway:
    container_name: playgo
    image: golang
    volumes:
      - ./:/go/src/github.com/user/playgo/
      - ./go/src:/go/src
    working_dir: /go/src/github.com/user/playgo/
    tty: true